### ISSUE TITLE
Não reproduz filmes/series

### ISSUE THREAD

**Issue by puling** [xventil/plugin.video.tugaflix#1]
Depois de uma instalação nova do Kodibuntu com o Kodi 16.1 Jarvis o addon não reproduz os fimes nem as series

[kodi_crashlog-20160501_102325.zip](https://github.com/xventil/plugin.video.tugaflix/files/244026/kodi_crashlog-20160501_102325.zip)

**Comment by joaoramos** [comment]
Também não funciona no Kodi 15.2 instalado no OpenELEC 6.0.3 (Raspberry Pi).

**Comment by ric1280** [comment]
Eu tenho o kodi no osmc instalado no raspberry pi e também não funciona. Não me aparece qualquer filme/série listado quer pesquise por nome quer pesquise por categoria. Inspeccionei o código do addon e de facto o link de pesquisa está bem porque quando tento abrir pelo browser funciona bem. Possivelmente falta algum url resolver ou algum filtro de conteúdo. 

Espero que consigas resolver isto, 
Muito Obrigado ;)

**Comment by xventil** [comment]
Boas.  Estive ausente.  Vou tentar pegar nisto novamente durante as férias de Natal,  sem promessas pois os donos do tugaflix não querem saber nem ouvir falar de addons para o kodi...

**Comment by henriquedesousa** [comment]
Vivas, espero que tenhas tido umas boas festas. Conseguiste algum progresso?

**Comment by fmeira** [comment]
Alguma novidade?

**Comment by m4xc4v413r4** [comment]
Isto morreu? Sou capaz de pegar nisto para uso pessoal mas se for para continuar aqui não tenho problema em ajudar e isto ficar na tua página.

**Comment by xventil** [comment]
estou encravado em 2 situações
uma o update que o site faz quando escolhes uma temporada para listar os episódios e o segundo stress é criar uma maneira de aparecer as imagens do google captcha no kodi para se resolver. 

se quiseres posso colocar a versão que estava a fazer aqui para tentares dar uma vista de olhos, toda a ajuda é bem vinda.

**Comment by m4xc4v413r4** [comment]
Pois, ontem reparei que um dos problemas era os captchas, tenho de ver se descubro como dar a volta a isso.

**Comment by xventil** [comment]
o ideal ( a meu ver) é conseguir mostrar o captcha no kodi, e o utilizador escrever a frase, consigo ter o link da imagem com o texto para se resolver, apenas não consigo mostrar a imagem no kodi e fazer o post do input do teclado

**Comment by m4xc4v413r4** [comment]
Boas, desculpa lá demorar a responder mas às vezes tenho muito trabalho e acabo por nem ver nada do assunto.

Pois essa seria a idea.

Eu já fiz aqui um codigozito para meter isso no ecrã e pedir o input do utilizador, ainda não testei. Amanhã se tiver tempo tento testar ou pelo menos meto aqui.

Aquilo basicamente abres um WindowDialog com uma ControlImage (que vai ser a que capturas do captcha), fazes show, depois usas o Keyboard para abrir o teclado e o getText para ver o que o user escreveu e um data.update com isso pra mandar para trás.

edit:. Então isto está assim neste momento.
Ainda não tentei ir buscar o link da imagem do captcha mas como disseste que sabes fazer isso fica tratado.
Já meti a imagem a aparecer no ecrã com o teclado e a guardar o input, falta agarrar nisso e fazer o post, e tratar um bug com a imagem ficar tipo em background, mas isso deve ser rápido, vou fazer uma procura no API do Kodi.

```
	capimg = link ou variavel com link da imagem aqui
	if capimg:
		img = xbmcgui.ControlImage(550,20,600,114,capimg)
		dlg = xbmcgui.WindowDialog()
		dlg.addControl(img)
		dlg.show()
		kb = xbmc.Keyboard('', 'Type the letters in the image', False)
		kb.doModal()
		kbinput = kb.getText()
		wdlg.close()

```

Isso meti dentro do teu `def encontrar_fontes_openload(url):`
Ver se digo qualquer coisa mais logo ou amanhã. Dá uma olhada que tu tens mais prática com Python.

**Comment by m4xc4v413r4** [comment]
Para testar o processo fiz um mini programita para ir buscar a imagem do captcha, fazer post do mesmo e ir buscar o link do filme depois disso. Já está tudo a funcionar, é integrar no plugin agora.

Ainda andas por aí?

**Comment by xventil** [comment]
Sim, vi agora os teus comentários, desculpa, mas o tempo tem sido escasso... vou já ver se consigo fazer alguma coisa. dou feedback, amanhã no max.

**Comment by m4xc4v413r4** [comment]
Ya é na boa, também não tenho tido muito tempo, maior parte do que andei a ver disto foi umas horitas nas ultimas duas semanas.

Ainda não vi aquilo da imagem vir para o ecrã com o teclado e a imagem ficar tipo em background. Tenho de ver isso se não um gajo não consegue ler aquilo bem para meter o código. Mas como disse já fiz o processo todo de ir buscar a imagem, fazer post do captcha e dai ir buscar o link do openload para o video.
Agora era mesmo só meter isso a funcionar no plugin, não tenho é experiência nenhuma com plugins do Kodi, e muito pouca de python, mas chego lá na mesma, perco é um bocado de tempo a procurar info que se calhar tu sabes de já ter feito plugins.

Um gajo havia de arranjar maneira de falar melhor que isto de falar num issue do github é uma caca xD

**Comment by xventil** [comment]
meti o teu codigo acima, e aparece certinho na app, Muito Obrigado!! e já agora, podes enviar a parte do post e de receberes o openload ( metia já isso no código e já se podia começar a testar a sério). Envia-me  um email que assim posso enviar-te o plugin já "final" e podemos falar melhor.

Muito Obrigado!!

**Comment by xventil** [comment]
Situação resolvida. Issue fechado
