### ISSUE TITLE
Não funciona na nova versão do Kodi!

### ISSUE THREAD

**Issue by nalc** [xventil/plugin.video.tugaflix#2]
Podes actualiza-lo?

**Comment by xventil** [comment]
Boas.  Estive ausente.  Vou tentar pegar nisto novamente durante as férias de Natal,  sem promessas pois os donos do tugaflix não querem saber nem ouvir falar de addons para o kodi...

**Comment by xventil** [comment]
Vou fechar pois não está depwndente da versão do kodi.  

Obrigado
