### ISSUE TITLE
Implementar no Covenant

### ISSUE THREAD

**Issue by FFY00** [xventil/plugin.video.tugaflix#3]
Olá, eu gostaria de usar o teu código para adicionar o tugaflix como uma source no Covenant. Como não existe nenhuma licença explicitada no repositório, tu tens todos os direitos ao código, por isso eu decidi perguntar se podia usar. Se quiseres até podes ser tu a fazer o port para o Covenant, apenas se estiveres interessado, claro. Eu apenas gostaria de saber se tu te opões ao que eu pretendo fazer. Caso tu me dês luz verde irei prosseguir com o port, baseado no teu código.

Obrigado,
Filipe

**Comment by xventil** [comment]
Boas,

Estás à vontade, para usares o código.

Alguma duvida ou questão que tenhas, estás à vontade para perguntar.

Peço só que me avises quando implementares para eu depois espreitar Hehehe.

Obrigado

Em 18/11/2017 12:24 da manhã, "Filipe Laíns" <notifications@github.com>
escreveu:

**Comment by FFY00** [comment]
Ok, obrigado. Ainda não sei quando vou fazer isso, será quando eu tiver mais tempo. Quando acabar eu digo alguma coisa aqui.
